server:
  port: 10000

spring:
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 150MB

  application:
    name: wanted-pre-onboarding-backend
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
#      ddl-auto: update
#      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
    database: postgresql

  profiles:
    include: KEY